name: Test
on:
  pull_request:
    branches:
      - main
jobs:
  test:
    uses: kuckjwi0928/github-reusing-workflow/.github/workflows/gradle-workflow.yaml@main
    with:
      environment: dev
      project: workflow-java-example
